# Generated by Django 4.1 on 2022-09-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_featured_img_course_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='technologies',
            new_name='technology',
        ),
    ]
