# Generated by Django 4.1 on 2022-09-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_notification_alter_student_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notification'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_text',
        ),
    ]
