# Generated by Django 4.1 on 2022-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_notification_student_notification_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_subject',
            field=models.CharField(max_length=250, null=True, verbose_name='Notification Subject'),
        ),
    ]
