# Generated by Django 4.1 on 2022-10-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_attemptquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='right_ans',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
