# Generated by Django 4.1 on 2022-10-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_studymaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='files',
            new_name='upload',
        ),
    ]
