# Generated by Django 4.1 on 2022-10-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_fags_alter_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name_plural': '17. Contact Us',
            },
        ),
    ]
