# Generated by Django 4.1 on 2022-10-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_student_otp_digit_student_verify_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_auth_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login_auth_otp',
            field=models.BooleanField(default=False),
        ),
    ]
